name: Test versions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [macos-13, macos-14,ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        if: ${{ runner.os == 'Linux' }}

      - name: Install tap
        if: matrix.os != 'macos-14'
        run: |
          brew tap pact-foundation/pact-ruby-standalone
          cd $(brew --prefix)/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone/
          git checkout ${{ github.sha }}
          brew install --verbose --debug pact-ruby-standalone
      - name: Install tap
        if: matrix.os == 'macos-14'
        run: |
          brew tap pact-foundation/pact-ruby-standalone
          cd $(brew --prefix)/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone/
          git checkout ${{ github.sha }}
          brew install --verbose --debug pact-ruby-standalone

      - name: Brew test tap
        run: |
          brew test pact-ruby-standalone

      - name: Test tap
        run: |
          pact
          pact-broker --help
          pact-message --help
          pact-mock-service --help
          pact-plugin-cli --help
          pact-provider-verifier --help
          pact-stub-service --help
          pactflow --help


      - name: Audit tap
        run: |
          brew audit --strict --online pact-ruby-standalone
